[package]
name = "ralp"
version = "0.1.0"
edition = "2021"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]
description = "Implementation of a DASH7 ALP protocol codec."
readme = "README.md"
repository = "https://github.com/vhdirk/ralp"
license = "MIT"
keywords = ["dash7", "alp", "parser", "protocol"]
categories = ["encoding", "parser-implementations"]

[dependencies]
modular-bitfield = { version = "0.11.2", git = "https://github.com/bramp/modular-bitfield.git", branch = "master"}
serde = { version = "1.0.147", features = ["serde_derive"] }

[dev-dependencies]
hex-literal = "0.3.4"
