[package]
name = "dash7"
version = "0.2.0"
edition = "2021"
authors = ["Dirk Van Haerenborgh <vhdirk@gmail.com>"]
description = "Implementation of a DASH7 ALP protocol codec."
readme = "README.md"
repository = "https://github.com/vhdirk/dash7-rs"
license = "MIT"
keywords = ["dash7", "alp", "parser", "protocol"]
categories = ["encoding", "parser-implementations"]

[dependencies]
deku = { version = "0.16.0", default-features = false }
bitvec = "1.0.1"
mutually_exclusive_features = "0.0.3"

[dev-dependencies]
hex-literal = "0.4.1"

[features]
default = ["std", "spec_v1_2"]
std = ["deku/std"]
alloc = ["deku/alloc"]

spec_v1_2 = []
subiot_v5_3 = []
wizzilab_v5_3 = []

[patch.crates-io]
# deku = { path = "../deku" }
deku = {git="https://github.com/vhdirk/deku" ,branch = "predicate-stop-when-empty"}